export const backgroundFragments = [{
  id: 1,
  src: '/background-mooon-1.svg',
  alt: 'background-moon-1',
  styleName: 'One',
  width: 944,
  height: 314,
}, {
  id: 2,
  src: '/background-mooon-2.svg',
  alt: 'background-moon-2',
  styleName: 'Two',
  width: 314,
  height: 944,
}, {
  id: 3,
  src: '/background-mooon-3.svg',
  alt: 'background-moon-3',
  styleName: 'Three',
  width: 314,
  height: 944,
}, {
  id: 4,
  src: '/background-mooon-4.svg',
  alt: 'background-moon-4',
  styleName: 'Four',
  width: 314,
  height: 944,
}]